version: '2'

volumes:
  postgres_data: {}
  mongodb_data: {}
  env: {}

services:
  app:
    build: .
    command: python -u __main__.py
    volumes:
      - .:/app
    ports:
      - '127.0.0.1:8080:8080'
    restart: always
    depends_on:
      - mysql
      - nosql
    # uncomment for debugging the service - container does not try to start dev server
    #entrypoint: ["sh", "-c", "sleep infinity"]
  mysql:
    #https://hub.docker.com/_/postgres/
    image: postgres:10-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: db_pwd
      POSTGRES_DB: hack_sabam
    ports: #make db accessible locally
      - '127.0.0.1:5433:5432'
  nosql:
    image: mongo:3.6.9
    volumes:
      - mongodb_data:/data/db
    ports:
      - '127.0.0.1:27019:27017'
